FROM node:14-alpine as frontend
WORKDIR /frontend
COPY ui/frontend/package.json ui/frontend/package-lock.json /frontend/
RUN npm install --production
COPY ui/frontend /frontend
RUN npm run build

FROM tensorflow/tensorflow:latest-py3

VOLUME  /repo
WORKDIR /repo/applications/smart-distancing

RUN apt-get update && apt-get install -y pkg-config libsm6 libxext6 libxrender-dev

RUN pip install --upgrade pip setuptools==41.0.0 && pip install opencv-python wget fastapi uvicorn aiofiles scipy image

COPY --from=frontend /frontend/build /srv/frontend

EXPOSE 8000

ENTRYPOINT ["python", "neuralet-distancing.py"]
CMD ["--config", "config-x86.ini"]
